### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by kernkode** [adri1336/vc-rp#2]
por que me sale eso? si no e movido nada?

`player/jobs/jobs/taxi.inc(333) : error 017: undefined symbol "Text_Format_TD"
player/jobs/jobs/taxi.inc(333) : warning 202: number of arguments does not match definition
player/jobs/jobs/taxi.inc(333) : warning 202: number of arguments does not match definition
player/jobs/jobs/taxi.inc(333) : error 029: invalid expression, assumed zero
player/jobs/jobs/taxi.inc(333) : error 017: undefined symbol "TEXTDRAW_TAXIMETER"
player/jobs/jobs/taxi.inc(333) : fatal error 107: too many error messages on one line`

**Comment by adri1336** [comment]
Comprueba que la versión de YSI es la que se indica en el readme, la función Text_Format_TD es una función de YSI

**Comment by adri1336** [comment]
Faltaba añadir YSI 4.0.2 a dependencias, gracias por el reporte.

**Comment by neiam00** [comment]
porque eres un cpaster
